### ISSUE TITLE
Invalid MySQL sintax

### ISSUE THREAD

**Issue by Phat3** [FernandoDoming/r2diaphora#1]
Hi,

I was trying to use this tool but during the schema creation it crashes because of several SQL syntax errors. The Readme says that one of the requirements is MySQL server but some SQL statements are not supported by it (specifically the syntax `CREATE INDEX IF NOT EXISTS ...` [is not supported](https://dev.mysql.com/doc/refman/8.0/en/create-index.html)). Swapping MySQL with MariaDB fixes all the problems though.

Is the Readme wrong?

**Comment by FernandoDoming** [comment]
Yes, you are indeed right, I have been using MariaDB for development and assumed the syntax would be the same. I will update the readme to reflect that. 

Thanks for reporting.

**Comment by Phat3** [comment]
No problem 👍
