### ISSUE TITLE
cant build r2ghidra - fails

### ISSUE THREAD

**Issue by MisterAero** [FernandoDoming/r2diaphora#2]
r2pm -ci r2ghidra
`
Cleaning r2ghidra...
Already up to date.
DEPENDS: r2ghidra-sleigh
Mon Nov 21 13:57:37 IST 2022
clean Done For r2ghidra
/home/aero/.local/share/radare2/r2pm/db/r2ghidra TGZ=
Cleaning up /home/aero/.local/share/radare2/r2pm/git//r2ghidra...
Cloning into 'r2ghidra'...
Submodule 'third-party/pugixml' (https://github.com/zeux/pugixml.git) registered for path 'third-party/pugixml'
Cloning into '/home/aero/.local/share/radare2/r2pm/git/r2ghidra/third-party/pugixml'...
Submodule path 'third-party/pugixml': checked out 'bcf483c3b71ac592b058d145fe6a579642b798e8'
DEPENDS: r2ghidra-sleigh
Mon Nov 21 13:57:37 IST 2022
Install Done For r2ghidra
git clone https://github.com/radareorg/ghidra-native
Cloning into 'ghidra-native'...
cd ghidra-native && git checkout 0.2.5
Note: switching to '0.2.5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6ce2dc2 Release 0.2.5
make -C ghidra-native patch
make[1]: Entering directory '/home/aero/.local/share/radare2/r2pm/git/r2ghidra/ghidra-native'
for a in patches/0001-space-after-comma.patch patches/0002-make-sleigharch-public.patch patches/0004-public-fields.patch patches/00067-readonly-warning.patch patches/0020-Fix-double-free-crash-when-deinitializing-multiple-X.patch patches/0022-Show-noreturn-information-in-function-signature-2.patch patches/0023-Undef-LoadImage-for-windows.patch patches/0024-ignore-symbol-beyond-space.patch patches/0044-bad-unicode-codepoint.patch patches/0055-datatype-clone.patch patches/0056-nullderef-workaround.patch patches/0080-getparent-flow.patch patches/0090-nocasts-warnings.patch ; do echo "patch -p1 < $a" ; patch -p1 < $a ; done
patch -p1 < patches/0001-space-after-comma.patch
patching file src/decompiler/printc.cc
Hunk #2 succeeded at 1907 (offset 46 lines).
Hunk #3 succeeded at 2006 (offset 46 lines).
Hunk #4 succeeded at 2025 (offset 46 lines).
Hunk #5 succeeded at 2478 (offset 46 lines).
patch -p1 < patches/0002-make-sleigharch-public.patch
patching file src/decompiler/sleigh_arch.hh
patch -p1 < patches/0004-public-fields.patch
patching file src/decompiler/context.hh
patching file src/decompiler/sleigh.hh
Hunk #1 succeeded at 167 (offset 1 line).
patch -p1 < patches/00067-readonly-warning.patch
patching file src/decompiler/funcdata_varnode.cc
patch -p1 < patches/0020-Fix-double-free-crash-when-deinitializing-multiple-X.patch
patching file src/decompiler/xml.cc
patching file src/decompiler/xml.hh
patch -p1 < patches/0022-Show-noreturn-information-in-function-signature-2.patch
patching file src/decompiler/prettyprint.cc
patching file src/decompiler/prettyprint.hh
patching file src/decompiler/printc.cc
Hunk #1 succeeded at 2358 (offset 46 lines).
patch -p1 < patches/0023-Undef-LoadImage-for-windows.patch
patching file src/decompiler/loadimage.hh
patch -p1 < patches/0024-ignore-symbol-beyond-space.patch
patching file src/decompiler/database.cc
patch -p1 < patches/0044-bad-unicode-codepoint.patch
patching file src/decompiler/stringmanage.cc
patch -p1 < patches/0055-datatype-clone.patch
patching file src/decompiler/type.hh
patch -p1 < patches/0056-nullderef-workaround.patch
patching file src/decompiler/merge.hh
patch -p1 < patches/0080-getparent-flow.patch
patching file src/decompiler/flow.cc
patch -p1 < patches/0090-nocasts-warnings.patch
patching file src/decompiler/printc.cc
Hunk #1 succeeded at 3097 (offset 2 lines).
Hunk #2 succeeded at 3106 (offset 2 lines).
touch patch.done
make[1]: Leaving directory '/home/aero/.local/share/radare2/r2pm/git/r2ghidra/ghidra-native'
checking build system type... x86_64-unknown-wsl-gnu
checking host system type... x86_64-unknown-wsl-gnu
checking target system type... x86_64-unknown-wsl-gnu
checking for working directories... current
using prefix '/usr'
checking for c++ compiler... c++
checking for cpp... cpp
checking for git... /usr/bin/git
checking for pkg-config... /usr/bin/pkg-config
Using PKGCONFIG: /usr/bin/pkg-config
checking pkg-config flags for r_core... yes
checking pkg-config flags for r_asm... yes
checking pkg-config flags for r_anal... yes
checking for r2... /usr/bin/r2
checking for bison... /usr/bin/bison
checking for flex... /usr/bin/flex
checking exec r2 -H R2_PREFIX... ok
checking exec r2 -H R2_USER_PLUGINS... ok
checking exec r2 -H R2_LIBR_PLUGINS... ok
creating config.mk
cleaning temporally files... done

Final report:
 - VERSION = 5.7.8
 - R2_PREFIX = /usr
 - PREFIX = /usr
 - PKGCONFIG = /usr/bin/pkg-config
make: Entering directory '/home/aero/.local/share/radare2/r2pm/git/r2ghidra/src'
c++ -fPIC -I../third-party/pugixml/src/ -g -std=c++11 -I/home/aero/.local/share/radare2/prefix/include -DR2GHIDRA_SLEIGHHOME_DEFAULT=\"/home/aero/.local/share/radare2/plugins/r2ghidra_sleigh\" -w -fPIC -Wshadow -I../ghidra-native/src/decompiler -I. -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -c R2Architecture.cpp
c++ -fPIC -I../third-party/pugixml/src/ -g -std=c++11 -I/home/aero/.local/share/radare2/prefix/include -DR2GHIDRA_SLEIGHHOME_DEFAULT=\"/home/aero/.local/share/radare2/plugins/r2ghidra_sleigh\" -w -fPIC -Wshadow -I../ghidra-native/src/decompiler -I. -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -c R2LoadImage.cpp
c++ -fPIC -I../third-party/pugixml/src/ -g -std=c++11 -I/home/aero/.local/share/radare2/prefix/include -DR2GHIDRA_SLEIGHHOME_DEFAULT=\"/home/aero/.local/share/radare2/plugins/r2ghidra_sleigh\" -w -fPIC -Wshadow -I../ghidra-native/src/decompiler -I. -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -c R2Scope.cpp
c++ -fPIC -I../third-party/pugixml/src/ -g -std=c++11 -I/home/aero/.local/share/radare2/prefix/include -DR2GHIDRA_SLEIGHHOME_DEFAULT=\"/home/aero/.local/share/radare2/plugins/r2ghidra_sleigh\" -w -fPIC -Wshadow -I../ghidra-native/src/decompiler -I. -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -I/usr/include/libr -I/usr/include/capstone -I/usr/include/libr -c R2TypeFactory.cpp
In file included from R2LoadImage.cpp:4:
R2Utils.h: In function ‘void r_interval_tree_foreach_cpp(RIntervalTree*, const F&)’:
R2Utils.h:16:2: error: ‘RIntervalTreeIter’ was not declared in this scope; did you mean ‘RIntervalTree’?
   16 |  RIntervalTreeIter it;
      |  ^~~~~~~~~~~~~~~~~
      |  RIntervalTree
R2Utils.h:17:7: error: ‘it’ was not declared in this scope; did you mean ‘int’?
   17 |  for (it = r_rbtree_first (&(tree)->root->node); r_rbtree_iter_has (&it); r_rbtree_iter_next (&(it))) {
      |       ^~
      |       int
R2Utils.h:18:25: error: there are no arguments to ‘r_interval_tree_iter_get’ that depend on a template parameter, so a declaration of ‘r_interval_tree_iter_get’ must be available [-fpermissive]
   18 |   RIntervalNode *node = r_interval_tree_iter_get (&it);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
R2Utils.h:18:25: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
R2LoadImage.cpp: In member function ‘virtual void R2LoadImage::getReadonly(RangeList&) const’:
R2LoadImage.cpp:43:5: error: ‘RIOMapRef’ was not declared in this scope; did you mean ‘RIOMapGet’?
   43 |     RIOMapRef *mapref;
      |     ^~~~~~~~~
      |     RIOMapGet
R2LoadImage.cpp:43:16: error: ‘mapref’ was not declared in this scope
   43 |     RIOMapRef *mapref;
      |                ^~~~~~
R2LoadImage.cpp:46:5: error: ‘RIOBank’ was not declared in this scope; did you mean ‘RIOBind’?
   46 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |     ^~~~~~~
      |     RIOBind
R2LoadImage.cpp:46:14: error: ‘bank’ was not declared in this scope
   46 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |              ^~~~
R2LoadImage.cpp:46:44: error: ‘RIO’ {aka ‘struct r_io_t’} has no member named ‘bank’
   46 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |                                            ^~~~
R2LoadImage.cpp:46:21: error: ‘r_io_bank_get’ was not declared in this scope; did you mean ‘r_io_map_get’?
   46 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |                     ^~~~~~~~~~~~~
      |                     r_io_map_get
R2LoadImage.cpp:47:54: error: ‘RIOMapRef’ is not a type
   47 |     r_list_foreach_cpp<RIOMapRef>(bank->maprefs, [&](RIOMapRef *mapref) {
      |                                                      ^~~~~~~~~
R2LoadImage.cpp: In lambda function:
R2LoadImage.cpp:48:46: error: request for member ‘id’ in ‘* mapref’, which is of non-class type ‘int’
   48 |      RIOMap *map = r_io_map_get (io, mapref->id);
      |                                              ^~
R2LoadImage.cpp:49:19: error: ‘r_io_map_begin’ was not declared in this scope; did you mean ‘r_io_map_resize’?
   49 |      ut64 begin = r_io_map_begin (map);
      |                   ^~~~~~~~~~~~~~
      |                   r_io_map_resize
R2LoadImage.cpp:50:17: error: ‘r_io_map_end’ was not declared in this scope; did you mean ‘r_io_map_add’?
   50 |      ut64 end = r_io_map_end (map);
      |                 ^~~~~~~~~~~~
      |                 r_io_map_add
R2LoadImage.cpp:72:23: error: ‘RCore’ {aka ‘struct r_core_t’} has no member named ‘rasm’
   72 |      int inc = (core->rasm->bits == 64)? 8: 4;
      |                       ^~~~
R2LoadImage.cpp: In member function ‘virtual void R2LoadImage::getReadonly(RangeList&) const’:
R2LoadImage.cpp:100:5: error: ‘RIOMapRef’ was not declared in this scope; did you mean ‘RIOMapGet’?
  100 |     RIOMapRef *mapref;
      |     ^~~~~~~~~
      |     RIOMapGet
R2LoadImage.cpp:100:16: error: ‘mapref’ was not declared in this scope
  100 |     RIOMapRef *mapref;
      |                ^~~~~~
R2LoadImage.cpp:103:5: error: ‘RIOBank’ was not declared in this scope; did you mean ‘RIOBind’?
  103 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |     ^~~~~~~
      |     RIOBind
R2LoadImage.cpp:103:14: error: ‘bank’ was not declared in this scope
  103 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |              ^~~~
R2LoadImage.cpp:103:44: error: ‘RIO’ {aka ‘struct r_io_t’} has no member named ‘bank’
  103 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |                                            ^~~~
R2LoadImage.cpp:103:21: error: ‘r_io_bank_get’ was not declared in this scope; did you mean ‘r_io_map_get’?
  103 |     RIOBank *bank = r_io_bank_get (io, io->bank);
      |                     ^~~~~~~~~~~~~
      |                     r_io_map_get
R2LoadImage.cpp:104:54: error: ‘RIOMapRef’ is not a type
  104 |     r_list_foreach_cpp<RIOMapRef>(bank->maprefs, [&](RIOMapRef *mapref) {
      |                                                      ^~~~~~~~~
R2LoadImage.cpp: In lambda function:
R2LoadImage.cpp:105:46: error: request for member ‘id’ in ‘* mapref’, which is of non-class type ‘int’
  105 |      RIOMap *map = r_io_map_get (io, mapref->id);
      |                                              ^~
R2LoadImage.cpp:106:19: error: ‘r_io_map_begin’ was not declared in this scope; did you mean ‘r_io_map_resize’?
  106 |      ut64 begin = r_io_map_begin (map);
      |                   ^~~~~~~~~~~~~~
      |                   r_io_map_resize
R2LoadImage.cpp:107:17: error: ‘r_io_map_end’ was not declared in this scope; did you mean ‘r_io_map_add’?
  107 |      ut64 end = r_io_map_end (map);
      |                 ^~~~~~~~~~~~
      |                 r_io_map_add
In file included from R2TypeFactory.cpp:12:
R2Utils.h: In function ‘void r_interval_tree_foreach_cpp(RIntervalTree*, const F&)’:
R2Utils.h:16:2: error: ‘RIntervalTreeIter’ was not declared in this scope; did you mean ‘RIntervalTree’?
   16 |  RIntervalTreeIter it;
      |  ^~~~~~~~~~~~~~~~~
      |  RIntervalTree
R2Utils.h:17:7: error: ‘it’ was not declared in this scope; did you mean ‘int’?
   17 |  for (it = r_rbtree_first (&(tree)->root->node); r_rbtree_iter_has (&it); r_rbtree_iter_next (&(it))) {
      |       ^~
      |       int
R2Utils.h:18:25: error: there are no arguments to ‘r_interval_tree_iter_get’ that depend on a template parameter, so a declaration of ‘r_interval_tree_iter_get’ must be available [-fpermissive]
   18 |   RIntervalNode *node = r_interval_tree_iter_get (&it);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
R2Utils.h:18:25: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
In file included from R2Architecture.cpp:8:
R2Utils.h: In function ‘void r_interval_tree_foreach_cpp(RIntervalTree*, const F&)’:
R2Utils.h:16:2: error: ‘RIntervalTreeIter’ was not declared in this scope; did you mean ‘RIntervalTree’?
   16 |  RIntervalTreeIter it;
      |  ^~~~~~~~~~~~~~~~~
      |  RIntervalTree
R2Utils.h:17:7: error: ‘it’ was not declared in this scope; did you mean ‘int’?
   17 |  for (it = r_rbtree_first (&(tree)->root->node); r_rbtree_iter_has (&it); r_rbtree_iter_next (&(it))) {
      |       ^~
      |       int
R2Utils.h:18:25: error: there are no arguments to ‘r_interval_tree_iter_get’ that depend on a template parameter, so a declaration of ‘r_interval_tree_iter_get’ must be available [-fpermissive]
   18 |   RIntervalNode *node = r_interval_tree_iter_get (&it);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
R2Utils.h:18:25: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
R2TypeFactory.cpp: In member function ‘Datatype* R2TypeFactory::queryR2(const string&, std::set<std::__cxx11::basic_string<char> >&)’:
R2TypeFactory.cpp:189:7: error: ‘R_TYPE_TYPEDEF’ was not declared in this scope
  189 |  case R_TYPE_TYPEDEF:
      |       ^~~~~~~~~~~~~~
In file included from R2Scope.cpp:13:
R2Utils.h: In function ‘void r_interval_tree_foreach_cpp(RIntervalTree*, const F&)’:
R2Utils.h:16:2: error: ‘RIntervalTreeIter’ was not declared in this scope; did you mean ‘RIntervalTree’?
   16 |  RIntervalTreeIter it;
      |  ^~~~~~~~~~~~~~~~~
      |  RIntervalTree
R2Utils.h:17:7: error: ‘it’ was not declared in this scope; did you mean ‘int’?
   17 |  for (it = r_rbtree_first (&(tree)->root->node); r_rbtree_iter_has (&it); r_rbtree_iter_next (&(it))) {
      |       ^~
      |       int
R2Utils.h:18:25: error: there are no arguments to ‘r_interval_tree_iter_get’ that depend on a template parameter, so a declaration of ‘r_interval_tree_iter_get’ must be available [-fpermissive]
   18 |   RIntervalNode *node = r_interval_tree_iter_get (&it);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
R2Utils.h:18:25: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
R2Scope.cpp: In lambda function:
R2Scope.cpp:175:34: error: ‘RAnalFunction’ {aka ‘struct r_anal_function_t’} has no member named ‘bp_off’
  175 |    int delta = var->delta + fcn->bp_off - extraPop; // not 100% sure if extraPop is correct here
      |                                  ^~~~~~
make: *** [Makefile:96: R2LoadImage.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:96: R2TypeFactory.o] Error 1
make: *** [Makefile:96: R2Scope.o] Error 1
make: *** [Makefile:96: R2Architecture.o] Error 1
make: Leaving directory '/home/aero/.local/share/radare2/r2pm/git/r2ghidra/src'
[31mERROR: [32mmake[0m
`

**Comment by FernandoDoming** [comment]
Hello,

That problem is specific to r2ghidra and as such there is nothing I can do on my end. I just tested in my system (ubuntu 22.04 x64 / radare2 5.7.7 28968 @ linux-x86-64 git.5.7.6-275-gb34220b3b commit: b34220b3b7ec637c7427c0e31ebbb27b23429e31 build: 2022-09-09__13:39:46) and r2ghidra builds fine. Best suggestion I can make is to open an issue in [r2ghidra's repo](https://github.com/radareorg/r2ghidra) stating your platform so they can reproduce. Alternatively, you can try compiling the radare version I am using and retrying.
